const treehouse_lyrics = [
    "do",
    "not",
    "enter",
    "is",
    "written",
    "on",
    "the",
    "doorway",
    "why",
    "can't",
    "everyone",
    "just",
    "go",
    "away",
    "except",
    "you",
    "can",
    "stay",
    "what",
    "think",
    "of",
    "my",
    "treehouse",
    "its",
    "where",
    "i",
    "sit",
    "and",
    "talk",
    "really",
    "loud",
    "usually",
    "i'm",
    "all",
    "by",
    "myself",
    "captain",
    "but",
    "be",
    "deputy",
    "glad",
    "so",
    "funny",
    "dont",
    "ever",
    "gonna",
    "let",
    "leave",
];

const mechanics = ["a", "to", "in", "with", "for", "as", "at", "from", "they", "our", "ing", "ly"];

const addtl_words = ["quiet", "loud", "together", "friend"];

export const WORDS = [...treehouse_lyrics, ...mechanics, ...addtl_words];
